M48
; DRILL file {KiCad (7.0.0-0)} date Sunday, February 26, 2023 at 09:06:09 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-26T21:06:09-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1063
%
G90
G05
T1
X5.5618Y-0.0079
X5.5618Y-0.1654
T2
X3.2992Y0.2677
X3.2992Y-0.6378
X5.5827Y0.2677
X5.5827Y-0.6378
T0
M30
